#!/usr/bin/env python3
"""Send processed replies as draft emails to a CS mailbox via SMTP.

This demo script scans the Excel queue for completed rows (status == 'done')
and emails the draft reply to a configured CS mailbox for human approval.

To avoid resending the same draft repeatedly, it keeps a CSV log of sent
items keyed by (id, finished_at).

Environment:
  SMTP_HOST, SMTP_PORT (default 587), SMTP_STARTTLS ("1"/"true"),
  SMTP_USERNAME, SMTP_PASSWORD, SMTP_FROM, SMTP_TO
"""

from __future__ import annotations

import argparse
import csv
import os
import smtplib
import ssl
from email.message import EmailMessage
from pathlib import Path
from typing import Set, Tuple

import pandas as pd


def _load_sent_log(path: Path) -> Set[Tuple[str, str]]:
    if not path.exists():
        return set()
    try:
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            return {(row.get("id", ""), row.get("finished_at", "")) for row in reader}
    except Exception:
        return set()


def _append_sent_log(path: Path, row_id: str, finished_at: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    is_new = not path.exists()
    with path.open("a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "finished_at"])
        if is_new:
            writer.writeheader()
        writer.writerow({"id": row_id, "finished_at": finished_at})


def _build_message(*, sender: str, recipient: str, subject: str, body: str) -> EmailMessage:
    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.set_content(body)
    return msg


def _send_message(host: str, port: int, starttls: bool, username: str | None, password: str | None, msg: EmailMessage) -> None:
    if starttls:
        context = ssl.create_default_context()
        with smtplib.SMTP(host, port) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            if username and password:
                server.login(username, password)
            server.send_message(msg)
    else:
        with smtplib.SMTP(host, port) as server:
            if username and password:
                server.login(username, password)
            server.send_message(msg)


def main() -> None:
    ap = argparse.ArgumentParser(description="Send queue 'done' replies to CS mailbox via SMTP")
    ap.add_argument("--queue", default="data/email_queue.xlsx", help="Queue workbook path")
    ap.add_argument("--log", default="data/drafts_sent_log.csv", help="CSV log of sent drafts")
    args = ap.parse_args()

    queue_path = Path(args.queue)
    if not queue_path.exists():
        raise SystemExit(f"Queue file not found: {queue_path}")
    try:
        df = pd.read_excel(queue_path)
    except Exception as exc:
        raise SystemExit(f"Unable to read queue workbook: {exc}")

    required_cols = {"id", "subject", "reply", "status", "finished_at"}
    missing = required_cols - set(df.columns)
    if missing:
        raise SystemExit(f"Queue workbook missing columns: {sorted(missing)}")

    sent_log_path = Path(args.log)
    sent_keys = _load_sent_log(sent_log_path)

    host = os.environ.get("SMTP_HOST") or "localhost"
    port = int(os.environ.get("SMTP_PORT") or 587)
    starttls = str(os.environ.get("SMTP_STARTTLS", "1")).lower() in {"1", "true", "yes"}
    username = os.environ.get("SMTP_USERNAME")
    password = os.environ.get("SMTP_PASSWORD")
    sender = os.environ.get("SMTP_FROM") or "no-reply@local"
    recipient = os.environ.get("SMTP_TO") or "cs-drafts@local"

    rows = df.copy()
    rows["status"] = rows["status"].astype(str).str.lower()
    candidates = rows[(rows["status"] == "done") & rows["reply"].astype(str).str.len().gt(0)]

    sent_count = 0
    for _, row in candidates.iterrows():
        key = (str(row.get("id", "")), str(row.get("finished_at", "")))
        if key in sent_keys:
            continue
        # Build a draft email to CS mailbox
        original_subject = str(row.get("subject", "")).strip()
        subject = f"Draft reply: {original_subject}" if original_subject else "Draft reply"
        body = str(row.get("reply", ""))
        # Include context for CS agents
        body_with_context = (
            f"[Draft generated by assistant]\n\n"
            f"Original subject: {original_subject}\n"
            f"Queue ID: {row.get('id')}\n\n"
            f"{body}"
        )
        msg = _build_message(sender=sender, recipient=recipient, subject=subject, body=body_with_context)
        _send_message(host, port, starttls, username, password, msg)
        _append_sent_log(sent_log_path, key[0], key[1])
        sent_count += 1

    print(f"Sent {sent_count} draft email(s) to {recipient}")


if __name__ == "__main__":
    main()

